[tool.poetry]
name = "projeto-pratico"
version = "0.1.0"
description = ""
authors = ["WS-Rodrigues <wendelsr2014@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
streamlit = "^1.61.1"
pandas = "^3.0.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
